"""Compile actionable facts into agent-native enforcement files.

Nothing here reads a fact body: an enforceable convention has to be stated in the
frontmatter, or it does not compile. Today the only target is Claude Code, which
gets a Stop hook per `enforce: stop` fact and a rules file per fact with `paths:`.
"""
from __future__ import annotations
import json
from pathlib import Path
import yaml
from .facts import Fact
from .space import Space

TARGETS = ("claude",)
LIVE_STATUS = ("active",)          # a superseded or disputed fact never gates a session
_CHECK_EOF = "MEMSPACE_CHECK_EOF"
_REASON_EOF = "MEMSPACE_REASON_EOF"


class CompileError(ValueError):
    pass


def _heredoc(text: str, delimiter: str, fact: Fact) -> str:
    if any(line.strip() == delimiter for line in text.splitlines()):
        raise CompileError(f"{fact.id}: text contains the heredoc delimiter {delimiter}")
    return f"<<'{delimiter}'\n{text}\n{delimiter}\n"


def hookable(facts: list[Fact]) -> list[Fact]:
    return [f for f in facts if f.status in LIVE_STATUS and f.enforce == "stop" and f.check]


def rulable(facts: list[Fact]) -> list[Fact]:
    return [f for f in facts if f.status in LIVE_STATUS and f.paths]


def render_hook(fact: Fact) -> str:
    """A Stop hook that blocks only on a check that ran and said no.

    Exit 0 lets the session stop, exit 2 blocks it and shows stderr to the agent. So
    every path that is not "the check ran and failed" — unparseable check, missing
    command, non-executable target — exits 0. A broken fact must never brick a session.

    Every invocation also appends one line to `$CLAUDE_PROJECT_DIR/.memspace/fire.log`
    (or `$PWD/.memspace/fire.log` if that var is unset): `FIRE` always, `BLOCK` only when
    the hook actually blocks. Logging can never affect the exit code — every step is
    guarded so a missing or read-only log location degrades silently.
    """
    reason = "\n".join(x for x in [
        fact.failure_if_ignored,
        f"memspace fact {fact.id} — {fact.summary}",
        f"check: {fact.check}",
    ] if x)
    memspace_log_fn = (
        "memspace_log() {\n"
        '  memspace_log_dir="${CLAUDE_PROJECT_DIR:-$PWD}/.memspace"\n'
        '  mkdir -p "$memspace_log_dir" 2>/dev/null || true\n'
        '  printf \'%s\\n\' "$*" >> "$memspace_log_dir/fire.log" 2>/dev/null || true\n'
        "}\n"
        "memspace_now() { date -u +%Y-%m-%dT%H:%M:%SZ; }\n"
    )
    return (
        "#!/usr/bin/env bash\n"
        f"# GENERATED by `memspace compile` from fact {fact.id}. Do not edit; edit the fact.\n"
        f"# {fact.title}\n"
        "set -u\n"
        "\n"
        + memspace_log_fn +
        f'memspace_log "FIRE $(memspace_now) {fact.id} stop"\n'
        "\n"
        "memspace_check=$(cat " + _heredoc(fact.check, _CHECK_EOF, fact) + ")\n"
        "\n"
        "# A check that does not even parse is a broken fact, not a violated convention.\n"
        'printf \'%s\\n\' "$memspace_check" | bash -n 2>/dev/null || exit 0\n'
        '\n'
        'bash -c "$memspace_check" >/dev/null 2>&1\n'
        "memspace_status=$?\n"
        "case $memspace_status in\n"
        "  0) exit 0 ;;              # the convention holds\n"
        "  126|127) exit 0 ;;        # the check could not run at all\n"
        "esac\n"
        "\n"
        "memspace_reason=$(cat " + _heredoc(reason, _REASON_EOF, fact) + ")\n"
        'printf \'%s\\n\' "$memspace_reason" >&2\n'
        f'memspace_log "BLOCK $(memspace_now) {fact.id} $(printf \'%s\\n\' "$memspace_reason" | head -n1)"\n'
        "exit 2\n"
    )


def render_rule(fact: Fact) -> str:
    front = yaml.safe_dump({"paths": list(fact.paths)}, sort_keys=False, allow_unicode=True,
                           default_flow_style=False).strip()
    body = [f"# [{fact.id}] {fact.title}", "", fact.summary]
    if fact.action_hint:
        body += ["", fact.action_hint]
    if fact.failure_if_ignored:
        body += ["", f"If ignored: {fact.failure_if_ignored}."]
    return f"---\n{front}\n---\n" + "\n".join(body) + "\n"


def render_settings(facts: list[Fact], existing: dict | None = None) -> str:
    data = dict(existing or {})
    hooks = dict(data.get("hooks") or {})
    hooks["Stop"] = [{"hooks": [{"type": "command", "command": f"bash .claude/hooks/{f.id}.sh"}
                                for f in facts]}]
    data["hooks"] = hooks
    return json.dumps(data, indent=2, sort_keys=True) + "\n"


def _write(path: Path, text: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")
    return path


def compile_space(space: Space, out: Path, target: str = "claude") -> list[Path]:
    """Write the target's enforcement files under `out`; return what was written."""
    if target not in TARGETS:
        raise CompileError(f"unknown target {target!r}; have {list(TARGETS)}")
    out = Path(out)
    facts = sorted(space.facts(), key=lambda f: f.id)
    written = []
    for fact in hookable(facts):
        written.append(_write(out / ".claude/hooks" / f"{fact.id}.sh", render_hook(fact)))
    for fact in rulable(facts):
        written.append(_write(out / ".claude/rules" / f"{fact.id}.md", render_rule(fact)))
    gates = hookable(facts)
    if gates:
        settings = out / ".claude/settings.json"
        existing = None
        if settings.is_file():
            try:
                existing = json.loads(settings.read_text(encoding="utf-8"))
            except json.JSONDecodeError as e:
                raise CompileError(f"{settings}: not valid JSON, refusing to overwrite ({e})") from e
        written.append(_write(settings, render_settings(gates, existing)))
    return sorted(written)
